resolver: lts-18.5
allow-newer: true
extra-deps:
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: e4d745b03bb69c088236c4cfe8918d815f24b075 # Tue Aug 17 2021
    subdirs:
      - . # liquidhaskell package itself
      - liquid-base
      - liquid-bytestring
      - liquid-containers
      - liquid-fixpoint # a git submodule
      - liquid-ghc-prim
      - liquid-parallel
      - liquid-platform
      - liquid-prelude
      - liquid-vector
nix:
  enable: true
  packages: [ z3 ]
